server {
	server_name vasper;
	root /nfs/homes/ibouchaf/Desktop/ooo;
	listen 3000;
	host 127.0.0.1;
	# client_max_body_size 100000000000000;
	index index.php;
	upload_path uploads/;

	error_page 404 data/error_pages/404.html;
	error_page 405 data/error_pages/405.html;
	error_page 500 data/error_pages/500.html;

	location / {
		root /nfs/homes/ibouchaf/Desktop/ooo;
		autoindex on;
		cgi	on;
		cgi_path /usr/bin/python3 /usr/bin/bash /usr/bin/php-cgi;
		cgi_extension .py .sh .php;
		index index.php;
		allow_methods POST DELETE GET;
	}

	location /auto {
		# root /home/astro/Desktop/vasper/data;
		autoindex on;
		allow_methods POST DELETE GET;
	}

	location /cgi {
		# root /home/astro/Desktop/vasper/data/cgi;
		cgi	on;
		autoindex on;
		cgi_path /usr/bin/python3 /usr/bin/bash /usr/bin/php-cgi;
		cgi_extension .py .sh .php;
		allow_methods POST DELETE GET;
	}

	location /vasper {
		return /;
	}

	location /vasper_website {
		root /home/astro/Desktop/vasper/data/vasper_website;
		autoindex on;
		index index.html;
		allow_methods POST DELETE GET;
	}

	location /videos {
		root /home/astro/Desktop/vasper/data/videos;
		allow_methods GET;
		autoindex on;
	}

	location /protected {
		root /home/astro/Desktop/vasper/data/protected;
		allow_methods GET;
		autoindex on;
	}

	location /error_pages {
		root /home/astro/Desktop/vasper/data/error_pages;
		allow_methods GET;
		autoindex on;
	}

	location /in {
		root /home/astro/Desktop/vasper/data;
		allow_methods DELETE;
		autoindex on;
	}

	location /uploads {
		root /home/astro/Desktop/vasper/data;
		allow_methods GET POST;
		autoindex on;
		index lol;
	}
}

server {
	server_name vasper2;
	root /nfs/homes/ibouchaf/Desktop/ooo;
	listen 3000;
	host 172.17.0.1;
	client_max_body_size 100000000000;
	index index.html;
	upload_path uploads/;

	# error_page 404 data/error_pages/404.html;
	error_page 405 data/error_pages/405.html;
	error_page 500 data/error_pages/500.html;

	location / {
		root /nfs/homes/ibouchaf/Desktop/ooo;
		autoindex on;
		index index.html;
		allow_methods POST DELETE GET;
	}
}

server {
	server_name vasper2;
	root /nfs/homes/ibouchaf/Desktop/ooo;
	listen 3000;
	host 192.168.122.1;
	client_max_body_size 100000000000;
	index index.html;
	upload_path uploads/;

	# error_page 404 data/error_pages/404.html;
	error_page 405 data/error_pages/405.html;
	error_page 500 data/error_pages/500.html;

	location / {
		root /nfs/homes/ibouchaf/Desktop/ooo;
		autoindex on;
		index index.html;
		allow_methods POST DELETE GET;
	}
}